version: '3.9'

services:

  psql:
    image: postgres:16-alpine3.17
    restart: always
    container_name: psql
    hostname: host-psql
    environment:
      TZ: America/Argentina/Buenos_Aires
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    volumes:
      - ./psql-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
